CREATE TABLE IF NOT EXISTS Countries (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(60) UNIQUE NOT NULL,
  iso3166_alpha2 CHAR(2) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(60) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Artists (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(60) NOT NULL,
  surname VARCHAR(60) NOT NULL,
  birth DATE NOT NULL,
  country INT NOT NULL,
  FOREIGN KEY (country) REFERENCES Countries (id)
);
